AllCops:
  TargetRubyVersion: 2.4

Style/FormatString:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200
