inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 6.0

Rails:
  Enabled: true

Style/FormatString:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - io
    - id
    - to
    - by
    - on
    - in
    - at
    - ip
    - db
    - n
    - q
