language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.5

services:
  - elasticsearch
  - redis-server

before_script:
  - cp config/secrets.yml.dist config/secrets.yml
  # Wait for Elasticsearch
  - sleep 10
  - bundle exec rake kkuleomi:index:init
