language: ruby
cache: bundler
rvm:
  - 2.5

gemfiles:
  - Gemfile
  - Gemfile.ci # rails 5

branches:
  only:
    - master

services:
  - elasticsearch
  - redis-server

before_install:
    - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
    - gem install bundler -v '< 2'

before_script:
  - cp config/secrets.yml.dist config/secrets.yml
  # Wait for Elasticsearch
  - sleep 10
  - bundle exec rake kkuleomi:index:init
